# Generated by Django 5.1.1 on 2024-10-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribe_optrion_alter_subscribe_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='optrion',
            new_name='option',
        ),
    ]
